export const ENDPOINTS = {
  auth: {
    register: "/auth/register",
    login: "/auth/login",
    forgotPassword: "/auth/forgot-password",
    resetPassword: "/auth/reset-password",
    verifyEmail: "/auth/verify-email",
    resendOtp: "/auth/resend-otp",
    getMe: "/users/me",
    logout: "/auth/logout",
  },
  company: {
    create: "/company",
    getAll: "/company",
    getMy: "/company/my",
    get: "/company/:companyId",
    update: "/company/:companyId",
    delete: "/company/:companyId",
  },
  job: {
    getAll: "/jobs",
    getMyJobs: "/jobs/me",
    stats: "/jobs/stats",
    create: "/jobs/create",
    createWithAI: "/jobs/create/ai",
    get: "/jobs/:jobId",
    update: "/jobs/:jobId",
    delete: "/jobs/:jobId",
    singleStats: "/jobs/:jobId/stats",
  },
  skills: {
    getAll: "/skills",
  },
  application: {
    publicApply: "/application/apply",
    getAll: "/application/company",
    getByJob: "/application/job/:jobId",
    get: "/application/:applicationId",
    updateStatus: "/application/:applicationId/status",
    delete: "/application/:applicationId",
    shortlist: "/application/:applicationId/shortlist",
  },
  questions: {
    getAll: "/question",
    getByJob: "/question/job/:jobId",
    get: "/question/:questionId",
    create: "/question",
    update: "/question/:questionId",
    delete: "/question/:questionId",
  },
  interview: {
    getMy: "/interview/company",
    getAll: "/interview",
    getDetails: "/interview/:token",
    getById: "/interview/detail/:interviewId",
    conversation: "/interview/conversation/:token",
    end: "/interview/end/:token",
    tts: "/interview/tts/:token",
  },
  candidate: {
    getMe: "/candidates/me",
    create: "/candidates/create",
    getAll: "/candidates",
    get: "/candidates/:id",
    update: "/candidates/:id",
    delete: "/candidates/:id",
  },
  user: {
    getMe: "/users/me",
    updateMe: "/users/me",
    deleteMe: "/users/me",
    getAll: "/users",
    get: "/users/:id",
    update: "/users/:id",
    delete: "/users/:id",
  },
  dashboard: {
    company: "/dashboard/company",
    admin: "/dashboard/admin",
  },
  applicationStats: {
    company: "/application/stats",
    admin: "/application/stats/admin",
  },
  interviewStats: {
    company: "/interview/stats",
    admin: "/interview/stats/admin",
  },
  aiSettings: {
    get: "/ai-settings",
    upsert: "/ai-settings",
    delete: "/ai-settings",
  },
  waitlist: {
    platformConfig: "/waitlist/platform-config",
    join: "/waitlist/join",
    checkEmail: "/waitlist/check/:email",
    createOrder: "/waitlist/payment/order",
    verifyPayment: "/waitlist/payment/verify",
  },
};
